version: '3'
services:
  
    image: php:8.1.1-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
   
networks:
  lamp-docker:
    driver: bridge
